#this scenario will be executed in case of creation of a Pull Request
name: pull request logic

#depends on the target branch one of the following scenarios:
on:
  pull_request:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'
    types: [opened, reopened, synchronize]


jobs:

  logger:
    runs-on: ubuntu-latest
    steps:
      - name: logger
        run: echo $GITHUB_BASE_REF