#this scenario will be executed in case of creation of a Pull Request 
name: pull request logic

#depends on the target branch one of the following scenarios:
on:
  pull_request:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'
    types: [opened, reopened, synchronize]


jobs:
  pre_deploy_logic:
    runs-on: ubuntu-latest
    steps:
      - name: Logger
        run: |
          echo "Event is:"
          echo -e "Pull request\n"
          echo "Pull request source branch is:"
          echo $GITHUB_HEAD_REF
          echo -e "\nPull request target branch is:"
          echo $GITHUB_BASE_REF
          

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: SFDX CLI installation
        run: |
          chmod +x ./build/install_dependencies.sh
          ./build/install_dependencies.sh


      - name: Salesforce org login
        run: |
          chmod +x ./build/login_to_SF_org.sh
          ./build/login_to_SF_org.sh

      #Deploy metadata to the target Salesforce org without saving
      #Apex tests execution
      - name: Predeploy actions
        run: |
          chmod +x ./build/pre_deploy_actions.sh
          ./build/pre_deploy_actions.sh